infinitered/ignite-andross

boilerplate/App/Containers/Styles/LaunchScreenStyles.js, boilerplate/App/Sagas/index.js, boilerplate/App/Themes/ApplicationStyles.js
Fixed broken Fonts reference in App/Themes/ApplicationStyles.js so the correct font is applied to the Launch Screen. I also updated the LaunchScreenStyles.js so the 'OPEN DEVSCREENS' button is not flush with the bottom of the LaunchScreen
Fixed the { takeLastest } import statement in App/Sagas/index.js so the import is from 'redux-saga/effects' rather than just 'redux/saga', which results in runtime errors reported in Xcode. See `https://github.com/redux-saga/redux-saga#sagasjs` to see why 'takeLatest' should be imported from 'redux-saga/effects' rather than from 'redux-saga'
=> fix fonts in ApplicationStyles & Sagas import

commands/listview.js
Running `ignite g listview TestRow --type=Row` fails with an exception because a variable is undefined. This change defines the variable. It also makes it so that `--dataType` can be passed as a parameter.
=> Fix generate listview with parameter

boilerplate/App/Config/ReduxPersist.js
I had someone complain in community.infinite.red and when I found their bug, it was because they didn't know it was rehydrating.  I think this is the second or third person to have this issue.   Let's turn this off bey default.  Next step, make it an opt-in plugin.
=> no rehydration by default - opt in only

boilerplate/App/Config/README.md, boilerplate/App/Config/ReactotronConfig.js, boilerplate/App/Containers/App.js
We never shipped Ignite with this turned on.
Should keep this turned on until we have reactotron plugin that asks.
=> adds image overlay feature from Reactotron

boilerplate/App/Components/DrawerButton.js, boilerplate/App/Components/FullButton.js, boilerplate/App/Components/RoundedButton.js
There's some confusion around why a component doesn't show up in the devscreens even when registered through `addComponentExample`. This clarifies that you also need to import your component somewhere in your application.
=> Adds clarification for addComponentExample usage

templates/screen.ejs
Seems that we were missing the appending of Screen in the generated screen file.
While it shouldn't cause any big issues, we do append `Screen` to the entered screen name in the CLI  [here](https://github.com/infinitered/ignite-ir-next/blob/master/commands/screen.js) and we do it in the 2016 boilerplate...just being consistent ;) 👍
=> Fix missing Screen append on screen name

boilerplate.js
With this change, we save about 18s on `ignite new X` by my calculations.
This also refactors the boilerplate generator code a bit. The primary change is that instead of shelling out an entire process to `ignite add` we just replicate the bare-bones parts of it we need here, shaving off a few seconds. Note that we do not do any cache-busting like `ignite add` does. From what I can tell, that is irrelevant here and adds 9 seconds to the time.
I was able to remove one unnecessary `yarn` call. I haven't found a situation where it's caused an issue, and I've tested it extensively here.
I also removed the Husky git hooks in this change because they were causing problems, although I left a TODO in there. I think we need to move that into a plugin.
I have a [companion …
=> Performance updates

boilerplate.js
Related to @skellock's comment here: https://github.com/infinitered/ignite/issues/985#issuecomment-296445504
This allows you to add the boilerplate plugin from a path rather than requiring it from npm.
=> References current boilerplate from dirname

boilerplate.js, boilerplate/Tests/Components/AlertMessageTest.js, boilerplate/Tests/Components/DrawerButtonTest.js, boilerplate/Tests/Components/FullButtonTest.js, boilerplate/Tests/Components/RoundedButtonTest.js, boilerplate/Tests/Redux/GithubReduxTest.js, boilerplate/Tests/Redux/LoginReduxTest.js, boilerplate/Tests/Sagas/GithubSagaTest.js, boilerplate/Tests/Sagas/LoginSagaTest.js, boilerplate/Tests/Sagas/StartupSagaTest.js, boilerplate/Tests/Services/FixtureAPITest.js, boilerplate/package.json.ejs, package.json, test/generators-integration.test.js, test/interface.test.js
Removed all AVA references and migrated existing tests to Jest for both the generator and the generated template.
=> Move from AVA to Jest

boilerplate/App/Components/DrawerButton.js, boilerplate/App/Components/FullButton.js, boilerplate/App/Components/RoundedButton.js, boilerplate/Tests/Components/AlertMessageTest.js, boilerplate/Tests/Components/DrawerButtonTest.js, boilerplate/Tests/Components/FullButtonTest.js, boilerplate/Tests/Components/RoundedButtonTest.js, boilerplate/Tests/Redux/LoginReduxTest.js, boilerplate/Tests/Services/FixtureAPITest.js, boilerplate/Tests/Setup.js.ejs, boilerplate/package.json.ejs
This completes the conversion from Ava to Jest tests.
1. package.json.ejs: Added script to update snapshots, removed react-native-mock and setup files in the jest block that were causing memory leak errors. 
2. Tests/Setup.js.ejs re-written to use jest mocks rather than using mockery. Includes support for components and their tests that use the react-native-i18n library. 
3. Re-wrote component tests to use snapshots to replace previous tests that used Enzyme/shallow to test the generated output. Because some people might want to use Enzyme/shallow for their component tests, I left in examples that exercise 'onPress' callbacks. This also shows that the shallow component tests are still working with jest.
4. Added more tests to the boilerplate (LoginReduxTest, FixtureApiTest) to improve …
=> Add jest-snapshot tests

boilerplate.js, boilerplate/Tests/Components/FullButtonTest.js, boilerplate/Tests/Components/RoundedButtonTest.js, boilerplate/package.json.ejs, package.json, templates/component.ejs, templates/container.ejs, templates/examples/GridExample.js.ejs, templates/examples/RowExample.js.ejs, templates/examples/SectionExample.js.ejs, templates/listview-sections.ejs, templates/listview.ejs, templates/screen.ejs, test/generators-integration.test.js
This removes Standard and other linting dependencies to make way for Standard to be installed as a plugin. 
https://github.com/infinitered/ignite-ir-next/issues/47
Removes `standard`, `babel-eslint`, `snazzy`, linting scripts and configuration from `package.json`
Adds a step to boilerplate install which installs standard from npm (https://github.com/robinheinze/ignite-standard) ...(NOTE: this shouldn't be merged until that plugin has been published to npm)
`ignite new` can be run with a `--no-lint` option to not install any linter at all. 
Updates integration tests and fixes a few instances of padded blocks that were being called out by Standard 10.0.2.
=> Standard Plugin

boilerplate/App/Config/ReactotronConfig.js, boilerplate/App/Containers/App.js, boilerplate/App/Redux/CreateStore.js, boilerplate/App/Services/Api.js, boilerplate/App/Services/RehydrationServices.js, boilerplate/package.json.ejs
This also fixes the issue of trying to use the Reactotron Overlay in production.
A few new features since 1.7:
* `reactotron-apisauce` is no longer needed.  we place our hooks at the `XMLHTTPRequest` level, so all networking requests are supported.  :tada:
* `AsyncStorage` is now tracked
* nicer serialization (we now can track falsy values and better circular dependency detection)
Fixes #49
=> Updates Reactotron to the latest version & techniques.

boilerplate.js, package.json, readme.md
Moving over to `ignite-ir-boilerplate` in the repo.
=> Renames ir-next to ir-boilerplate

boilerplate.js, lib/react-native-version.js, readme.md, test/react-native-version.test.js
Makes this a thing:
```sh
ignite new TheFuture --react-native-version 0.44.2
```
The boilerplate still recommends `0.42.0` (for now), but this allows people to do what they want.
=> Targetting different versions of React Native

lib/react-native-version.js
React Native 0.42.0 on Android is currently blowing up due to binaries in maven being nuked.
This allows us to dodge for now.
0.45 is coming out in a few days, so we'll likely skip up to that shortly.
=> Upgrades to 0.42.3 which fixes upstream RN Android issues.

boilerplate/package.json.ejs
This fixes warnings displayed when running Component tests that reference Enzyme.
Here is the result of running tests before the fix:
Here is the result of running tests after the fix:
=> Fix enzyme warnings

templates/examples/GridExample.js.ejs, templates/examples/RowExample.js.ejs, templates/examples/SectionExample.js.ejs, templates/listview-sections.ejs, templates/listview.ejs
Since state might be updated asynchronously, we shouldn't rely on it when calculating the next state. Instead we can pass setState a **function** that accepts the previous state and outputs a new state, rather than an **object** that references the current state as is currently implemented.
More info is available in the [React docs](https://facebook.github.io/react/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) and [this article](https://medium.freecodecamp.com/functional-setstate-is-the-future-of-react-374f30401b6b).
Not trying to nitpick, especially since the only code changing is in comments, but figured since so many people learn RN using Ignite (like I did) it's might help someone out down the line to see a functional setState in action.
=> Switching to functional setState in listview and examples

boilerplate/App/Config/index.js
For font scaling to be controllable it can't get garbage collected, so it has to live non-lazy.
=> fixes scaling encapsulation

boilerplate/package.json.ejs
Fix for when `console.tron.log()` appears in a `catch` block.
https://github.com/infinitered/babel-plugin-ignite-ignore-reactotron/pull/1
=> Bumps babel-plugin-ignite-ignore-reactotron.

templates/screen.ejs
After this change was commited:
https://github.com/infinitered/ignite-ir-boilerplate/commit/07d9eca7bbea251041422056d9cdc98f63f69498#diff-3a74efcd1a718d70ff863907651feec0, we need to remove the extra "Screen" that is appended to the name.
If I run the command
`ignite generate screen Testing`, 
the generated screen file will have 
`class TestingScreenScreen extends React.Component {`
This PR fixes this issue.
=> removed appending of "Screen" to name, as the name already ends with "Screen"

boilerplate/package.json.ejs
`apisauce@<=0.14.0` didn't play nice with `react-native@0.45.1` because of a build-time 3rd party lib we were using in `apisauce` that mucking about with monkey patching global variables. 😨 
All fixed up and shipped... and this brings `ignite-ir-boilerplate` up as well.
(also snuck `ramda` in here as well since `apisauce` uses the latest there).
=> Bumps apisauce & ramda.

boilerplate/App/Transforms/ConvertFromKelvin.js
=> Fixed typos: celcius -> celsius, farenheit -> fahrenheit

boilerplate/App/Services/ImmutablePersistenceTransform.js
Fixes #77, which is related to [this issue](https://github.com/infinitered/ignite/issues/271) and it appears [this line](https://github.com/infinitered/ignite-ir-boilerplate/blob/7a08b490fb49e745401ed75bc2f5ac251f098bdf/boilerplate/App/Services/ImmutablePersistenceTransform.js#L29) that is causing it. As @skellock speculated, this seems unnecessary as of [this merge request](https://github.com/rt2zz/redux-persist/pull/216/files). Removing the line resolves the issue.
=> Fixed issue with nested reducers

boilerplate/package.json.ejs
So `babel-preset-react-native` is still broken/not-published upstream.
https://github.com/infinitered/ignite/issues/1098#issuecomment-315170624
This locks us to `2.0.0` which works.
=> Adds a temp fix to repair broken rn preset.

boilerplate/package.json.ejs
Disabled git hooks to run tests in precommit and prepush until Enzyme becomes compatible with newer React Native versions. See issue 1109 in ignite: https://github.com/infinitered/ignite/issues/1109
I hope the format is correct. I have no idea if comments (or generally tags) can be multiline in ejs. I Couldn't find anything about it in the docs, which are pretty short :)
=> Disabled git hooks to run tests

boilerplate/ignite.json.ejs
Sets askToOverride to true in the default config. Without, its possible to overwrite previously generated components if you re-run the ignite generate action a second time.  Seems to be the expected behavior and thus better for the default.
Refers to Issue [1120](https://github.com/infinitered/ignite/issues/1120)
=> Add askToOverride to default config.

boilerplate/App/Sagas/index.js
Because of the following error message: `[...effects] has been deprecated in favor of all([...effects]), please update your code` (see redux-saga/redux-saga#960), the code needs to be updated (I know, very small contribution 😄).
=> Modification of the yeld due to an obsolete manner

boilerplate/package.json.ejs, lib/react-native-version.js, readme.md
Upgrades the boilerplate to RN 0.47.2
Due to various errors, also updates redux-saga and babel-preset-react-native
The app runs out of the box, tests pass, all default plugins work, dev screens work, generators seem to work. If there's anything else that should be tested, let me know. 
ignite-maps will break with this change (See https://github.com/airbnb/react-native-maps/issues/1193), so we should upgrade the version of react-native-maps once this is released.
=> Upgrade to RN 0.47.2

commands/list.js, templates/flatlist-grid-style.ejs, templates/flatlist-grid.ejs
flatlist grid is completely different logic than anything else, and was causing a yellowbox on RN 0.47.2
1. This PR fixes flatlist grids
2. You still get yellowbox on Sectioned Grids.  I have filed a ticket here on RN: https://github.com/facebook/react-native/issues/15772
3. Listview Sectioned Grids stopped working at some point... I'm not including the fix or taking it into account here, but this appears to be a regression, and probably needs an upstream ticket.  Unless someone (@fvonhoven et al.)  can figure out a new way to get it working.   The stack overflow solution (which was the same as our solution) nolonger works.
=> Flatlist yellowbox removed

boilerplate/Tests/Setup.js.ejs
react-native-device-info was removed in https://github.com/infinitered/ignite-ir-boilerplate/commit/6fe2841aac81715f950bce2664e4bda8c58170d3, so the test setup was failing on a fresh-from-the-oven app 
I left it commented as an example in case someone wondered what that file is for (it just says jest if you don't use i18n).
=> fix test setup from missing dependency

boilerplate/App/Containers/App.js, boilerplate/App/Redux/CreateStore.js, boilerplate/App/Redux/index.js
It took me 15 hours to figure that it was as simple than this. The looooooooonnnngest fix I've ever made.
But as always, success ! 
- HMR works as expected for components
- reducers are editable and state is kept between reloads
- sagas are cancelled and reloaded
- linting should be OK this time ;)
Todo:
- something could be tried to do the same with sagas if needed -> https://stackoverflow.com/questions/37148592/redux-saga-hot-reloading
<3
=> FIX - HMR now fully works

boilerplate.js, lib/react-native-version.js
One big change is that RN now uses a single index.js and App.js entrypoint (https://github.com/facebook/react-native/commit/6e99e314b232c315628c31f97a865c17c071ad23).
Another big change is that PropTypes is now officially out.  This means the dev-screens result in a Red Box until https://github.com/infinitered/ignite-dev-screens/pull/7 is merged and a new release is made.
=> upgrade react-native to v0.49.3

boilerplate/Tests/Components/DrawerButtonTest.js
It looks like this test file had a CMD+C CMD+V bug ;-)
I am just learning React, React-Native, and jumped it with both feet using the ignite-cli. I noticed this typo while reviewing the generated app trying to figure out how this all works.
=> Correcting test name.

boilerplate/.env.example
If the file is located inside previous path the `.env` file is never loaded. 
The file must be placed in the root path just like it says in the Readme.
>### Get started:
>1. **Copy .env.example to .env**
=> fixes .env copy location message

boilerplate.js
At the moment the `.env` file is ignored by Git. It shouldn't. This removes it from `.gitignore`.
=> Remove .env.example from gitignore

boilerplate.js
Sorry guys, it went to fast, changed wrong file.
This fixes https://github.com/infinitered/ignite-ir-boilerplate/pull/163
Include: `.env.example`
Exclude: `.env`
=> Include .env.example and ignore .env

boilerplate/package.json.ejs
If the route to the folder where we have the project had a folder named `Tests`( e.g. `~/Documents/Tests/MyAwesomeProject`), Jest was looking for tests outside the `<root>/Tests` folder.
=> fixes #169 : "testMatch not working properly"

boilerplate/package.json.ejs
=> Fixes  FAIL  Tests/StoriesTest.js

templates/flatlist-sections.ejs
no data prop for SectionList (the "data" property is sections)
`data={this.state.dataObjects}` - probably leftover from flatlist-grid.ejs
=> Remove data prop from SectionList

boilerplate/package.json.ejs
Addresses https://github.com/infinitered/ignite-ir-boilerplate-andross/issues/120
Removes husky and git-hooks scripts from the boilerplate package.json
=> Remove husky and precommit, prepush, and git-hook scripts

boilerplate/package.json.ejs
Per a Github [security alert](https://github.com/infinitered/ignite-ir-boilerplate-andross/network/alert/package-lock.json/lodash/open), this upgrades lodash to the latest version.
=> Security: Upgrade lodash

boilerplate.js, boilerplate/package.json.ejs
• Adds `awaits` to async functions. (their absence was causing missing dev screens)
• Adds `react-native-device-info`, which is required in order for `ignite-dev-screens` to work. The DeviceInfo screen uses this.
=> Add awaits, add dependency for ignite-dev-screens

boilerplate.js
Ignite was recently updated to allow version specifications, which caused Andross to install the specified versions of plugins rather than the latest.  
This specifically affects:
- `ignite-dev-screens@2.3.0` which installs an incompatible `react-navigation` (fixed in v2.4.2).
- `ignite-redux-persist@5.10.0` which doesn't exist.  The latest release is actually v1.1.2
This fixes them to install the specified version.
Related to https://github.com/infinitered/ignite/pull/1331
=> fix version specification for ignite plugins

lib/react-native-version.js
Update of React Native to fix the simulator issue on macOS https://github.com/infinitered/ignite-andross/issues/263
=> Xcode Simulator not found when running ios from a new Ignite project

boilerplate/App/Navigation/ReduxNavigation.js, boilerplate/App/Redux/CreateStore.js
I had a problem with my react-native-camera (black screen after changing tabs) and deeper investigation on it was resolved with joining redux navigation middleware to one initialization.
https://github.com/react-navigation/redux-helpers/issues/53
https://github.com/moaazsidat/react-native-qrcode-scanner/issues/177
=> Join Redux navigation middleware 
