infinitered/ignite-andross

commands/listview.js
templates/listview-grid-style.ejs
templates/listview-sections.ejs
templates/listview.ejs

Listview gen now allows grid sections

Update listview gen

---

test/generators-integration.test.js

Same fixes as https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/23

Fixes the integration tests.

---

readme.md

This PR will add a note in `README.md` about premium support offered by Infinite Red.
@GantMan

Add readme support

---

commands/listview.js

fix non-existing function

---

boilerplate.js
boilerplate/Tests/Setup.js

Should be very similar to https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/20. Thanks to @ruddell for the code!
Fixes #13

Removes extra i18n references when i18n not added -- tests pass

---

commands/container.js
commands/listview.js
commands/screen.js
lib/patterns.js
package.json

Fixes https://github.com/infinitered/ignite/issues/988 caused by #22

Fixes broken JS files and includes lib in npm package.

---

boilerplate.js

Specify RN version for `install()` of boilerplate

Specify RN version for `install()`

---

.gitignore
boilerplate.js
commands/screen.js

Fixes #2. Related to https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/38

Properly appends Screen to name in screen generator

---

boilerplate.js

Looks a little nicer, I think. Also includes more help. We really need better documentation around the app structure though. Working on that.

Changes success message

---

screenExamples.js

Updates more templates to include .ejs extensions

---

boilerplate.js
package.json
test/generators-integration.test.js

Pin versions & run integration tests in separate folder

---

boilerplate/App/Navigation/AppNavigation.js

All the changes are documented here: https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

Fix navigation header config

---

commands/container.js
commands/screen.js

Fixes https://github.com/infinitered/ignite/issues/1063

Fixes logging error in screen & container generators.

---

templates/screen.ejs

This fix for https://github.com/infinitered/ignite/issues/1070 is good to go

screen generator fixed

---

lib/react-native-version.js

this will allow us to build with 0.45 when using the template.

upgrade to 0.45 tested!

---

boilerplate/App/Config/ReduxPersist.js
boilerplate/App/Containers/RootContainer.js
boilerplate/App/Navigation/ReduxNavigation.js
boilerplate/App/Redux/CreateStore.js
boilerplate/App/Redux/NavigationRedux.js
boilerplate/App/Redux/ScreenTrackingMiddleware.js
boilerplate/App/Redux/index.js

So sorry, @derekgreenberg -  Somehow it wouldn't take updated pushes to this origin!
I think bc I had an old .git form the previous name!   Here's your suggestion enacted!

Connect to redux2

---

templates/listview-sections.ejs

listview naming fix

---

boilerplate.js
lib/patterns.js

Ref: https://github.com/infinitered/ignite/issues/1084

Updates file pattern for multi-line insert per Ignite-CLI issue #1084

---

templates/listview-sections.ejs

Found this via tests:  https://semaphoreci.com/ir/ignite/branches/master/builds/878
YAY TESTS FIND THINGS!!!

missed one spot - fixed now

---

templates/component-style.ejs

Maybe it was a metric from the old version?

Removed non-existent metric

---

boilerplate/App/Components/AlertMessage.js
boilerplate/App/Components/DrawerButton.js
boilerplate/App/Components/FullButton.js
boilerplate/App/Components/RoundedButton.js
boilerplate/App/Components/SearchBar.js
boilerplate/package.json.ejs
templates/component.ejs

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

Replaced React.PropTypes with prop-types package

---

boilerplate/App/Components/AlertMessage.js
boilerplate/App/Components/FullButton.js
boilerplate/App/Components/RoundedButton.js
boilerplate/App/Components/SearchBar.js
boilerplate/App/Containers/LaunchScreen.js
templates/component.ejs
templates/container.ejs
templates/examples/GridExample.js.ejs
templates/examples/RowExample.js.ejs
templates/examples/SectionExample.js.ejs
templates/listview-sections.ejs
templates/listview.ejs
templates/screen.ejs

So i messed up rebasing :(. So here is a new PR
@jamonholmgren there is something wrong with the yarn registery so thats why the check is failing

extends Component consistency

---

boilerplate/package.json.ejs

So we don't get the constant warning anymore :)

Bumb reactotron-react-native

---

commands/list.js

Fixed typo preventing sectioned lists from working correctly.

Fix sectioned list generator

---

boilerplate/App/Containers/App.js

For an unknown reason there is still an error at first HMR but the state is being updated.
Hard to understand what happens but as we can now update the store on the fly, I PR.
<3

FT - enable HMR for reducers/sagas/containers

---

commands/component.js
test/generators-integration.test.js

In a recent project, I felt the need for group components in folders. For example, a custom header with its own action buttons and other components.
This command will help a lot to keep it organized.
ps: Tests included

Allows to create folder-components

---

boilerplate/App/Redux/GithubRedux.js
boilerplate/App/Sagas/StartupSagas.js
templates/redux.ejs
templates/saga.ejs

Have selectors inside the redux files

---

commands/component.js
readme.md
test/generators-integration.test.js

Based on #148, refactor #167 and add docs.
Thanks for the better way of doing it @baldursson

Improves the folder/relative path components, also adds docs

---

boilerplate.js

Addresses https://github.com/infinitered/ignite-ir-boilerplate/issues/162
Many thanks to @Amurmurmur

Bump ignite-redux-persist version to support redux-persist v5

---

boilerplate/ignite.json.ejs

This will fix https://github.com/infinitered/ignite/issues/1200

Fix typo on the configuration

---

readme.md
templates/saga-test-ava.ejs
templates/saga-test-jest.ejs

And add information in the README about how to enable tests in the generators.

Fixing bug in template when test generation is enabled.

---

readme.md

Fix RN version

---

boilerplate.js
boilerplate/ignite.json.ejs
package-lock.json
package.json
readme.md

In preparation of renaming this repo. This updates the package json to reflect the new package name and anywhere in the code that referenced ignite-ir-boilerplate-andross.
This will need to be merged after renaming the repo.

Repo name updates

---

boilerplate.js

Necessary in order to conditionally patch out examples

Change order of dev-screen install

---

commands/generate/list.js

I m not sure. `toolbox.prompt.ask` need fix. but its fixing this issue.
https://github.com/infinitered/ignite-andross/issues/255

Fix broken list generation

---

boilerplate/App/Redux/CreateStore.js
boilerplate/package.json.ejs

fix(boilerplate): Run sagaMiddleware && update reactotron-redux-saga

---

boilerplate/package.json.ejs

close https://github.com/infinitered/ignite-andross/issues/272

fix(boilerplate): add missing devDeps to run storybook after init

---

boilerplate.js
boilerplate/package.json.ejs
lib/react-native-version.js
package.json
readme.md

Version 1.6.1 causes problems compiling in android https://github.com/facebook/react-native/issues/25294#issuecomment-503024749

Update default react-native-device-info to 2.1.3

---

boilerplate/App/Redux/ScreenTrackingMiddleware.js

Only use console.tron.log in dev mode
